### PR TITLE
Vue rewrite

### PR DESCRIPTION
**Pull request by miller-kevin**
Here's the first pass at the vue rewrite. All 3 primary functionalities work. Wouldn't complain if anyone wanted to help test it. It's currently stationed in a subfolder because I'm sure you don't want to totally remove the jquery version.

As a heads up, there were some changes made for use in my org. They're strictly styling changes, but things like transparent backgrounds so the grey doesn't stick out like a sore thumb were the biggest. Those are included here because I think transparent backgrounds should be the default.

You'll also notice that it no longer respects data attributes or classes set on the root level. We can add props to make those more usable, but I don't think it's necessary.

Side note: I just realized I actually didn't work from the latest branch. I'll handle merging in animateOnView tomorrow

### CODE REVIEW

**Comment by teobais** [comment]
@miller-kevin thank you for this work. Is it only my local environmental that gets a `sh: vue-cli-service: command not found` when I try to run it, or do you also have it on a fresh installation?

**Comment by miller-kevin** [comment]
@teobais no, I've never seen that error. Looks like the Vue cli GitHub has some answers https://github.com/vuejs/vue-cli/issues/2404

Also, if you're trying to run it, make sure you're running npm install first, then npm run serve in the directory

**Comment by miller-kevin** [comment]
@teobais Took another pass as this. Added animate on scroll and the demo page as you requested. Bunch of styling bug fixes as well

**Comment by teobais** [comment]
@miller-kevin thanks for the update. Does that mean we are ready for review? If so, I'll do my best to have a look at in the weekend. Also, I see two GitHub accounts of yours here. Which one would you prefer to be mentioned in the contributors list?

**Comment by teobais** [comment]
@miller-kevin another thing I neglected mentioning so far is the size variety: does the proposed solution still offer at least three pre-set sizes to choose from (small, default, big) as the jquery solution does?

**Comment by miller-kevin** [comment]
@teobais if there are two accounts, I'm guessing it's because I changed my old username from whoisme555 to miller-kevin, so miller-kevin would be preferred.

I believe it's ready for review, yes.

As for size configuration, I can add that. I removed it because it's just changing font size, so I didn't see the value in having presets that the user will just override anyways. I'll leave that up to you if you want it added back

**Comment by teobais** [comment]
@miller-kevin yes, please, let's keep it for the time-being.

**Comment by miller-kevin** [comment]
@teobais Alright, additional sizes added

**Comment by teobais** [comment]
@miller-kevin thank you again for this contribution. Would you mind letting me know of the name of your company and how you use percircle? I'm creating an inventory of enterprise use cases of percircle. If not able to share here, my social DMs are open. Thank you again, highly appreciated.

**Comment by miller-kevin** [comment]
@teobais I've used this at Accent Technologies. It's used in a part of the application meant to display sales lead quality and allow managers to get a display of a seller's performance at a glance. We initially had a jQuery solution and I've been slowly migrating us to Vue, so this change has been on my radar for a while anyways.

**Comment by teobais** [comment]
@miller-kevin seems like there are few companies with the same name, could you please provide a link? Also, please let me know if your company would have any objection to being listed as a percircle user some time in the future 

Another thing is that the language tag of the current repo seems to have changed to Vue, which shouldn't be the case, but I guess the heavy package-lock.json is to blame for :) . That being said, I consider transferring the vuejs port to a new repo, after making a few changes. Would you be interested in being listed a collaborator/maintainer there?

**Comment by miller-kevin** [comment]
@teobais https://accent-technologies.com/ I don't know if they'd object. I assume they'd be fine with it.

A new repo makes sense for something like this. Would be more clear to users if they could run something like npm install percircle-vue instead of manually adding the file to their solution. I don't mind being listed as a collaborator/maintainer. I can contribute as time permits

**Pull request merged**
